// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBex3MDG879_yhmhJBhj1aaZf455fvevvU',
    appId: '1:826637584384:web:599d770cc993645539b0e5',
    messagingSenderId: '826637584384',
    projectId: 'student-teacher-flutter-app',
    authDomain: 'student-teacher-flutter-app.firebaseapp.com',
    storageBucket: 'student-teacher-flutter-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDfWZvzKnaT7GZtiHM-y9CAqiIrYLwh8k',
    appId: '1:826637584384:android:c073ae1a211a3e5239b0e5',
    messagingSenderId: '826637584384',
    projectId: 'student-teacher-flutter-app',
    storageBucket: 'student-teacher-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ETT1uW2r0NDTigxR5VOHPz9vJd2iwGc',
    appId: '1:826637584384:ios:eaaba454ff59414e39b0e5',
    messagingSenderId: '826637584384',
    projectId: 'student-teacher-flutter-app',
    storageBucket: 'student-teacher-flutter-app.appspot.com',
    iosClientId: '826637584384-ps2dh3gdnaedjv2chbo8tcg46mlr5fpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackthon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ETT1uW2r0NDTigxR5VOHPz9vJd2iwGc',
    appId: '1:826637584384:ios:ce05d946e068b19139b0e5',
    messagingSenderId: '826637584384',
    projectId: 'student-teacher-flutter-app',
    storageBucket: 'student-teacher-flutter-app.appspot.com',
    iosClientId: '826637584384-nq0t92cg45sfd4p88nmoc6bm5bt4364a.apps.googleusercontent.com',
    iosBundleId: 'ancle',
  );
}
